image: node:8.12.0

cache:
  paths:
    - node_modules/

stages: 
  - test
  - build
  - deploy

test: 
  stage: test
  only:
    - master
  script: 
    - echo 'tests passed'

build: 
  stage: build
  only:
    - master
  script: 
    - npm install
    - npm run build

deploy_firebase:
  stage: deploy
  only: 
    - master
  script:
    - npm run deploy:ci
    
  